export const lightTheme = {
  body: "#ffa781",
  text: "#5b0e2d",
  toggleBackground: "#5b0e2d",
  button: "#5b0e2d",
  buttonText: "#ffffff",
  buttonHover: "#ffa781",
  buttonFocus: "#ffa781",
  inputBorder: "	#DCDCDC",
  inputBackground: "",
  inputBackgroundHover: "#fafafa",
  inputBackgroundFocus: "#fafafa",
  inputFocusShadow: "#ffa781",
  radioBorder: "#5b0e2d",
  radioBorderHover: "#5b0e2d",
  radioBackgroundCheck: "#5b0e2d",
  radioBorderChecked: "#5b0e2d",
  spinnerColor: "#5b0e2d",
  tableTextColor: "black",
};

export const darkTheme = {
  body: "#5b0e2d",
  text: "#ffa781",
  toggleBackground: "#ffa781",
  button: "#ffa781",
  buttonText: "#ffffff",
  buttonHover: "#5b0e2d",
  buttonFocus: "#5b0e2d",
  inputBorder: "	#DCDCDC",
  inputBackground: "",
  inputBackgroundHover: "#fafafa",
  inputBackgroundFocus: "#fafafa",
  inputFocusShadow: "#5b0e2d",
  radioBorder: "#ffa781",
  radioBorderHover: "#ffa781",
  radioBackgroundCheck: "#ffa781",
  radioBorderChecked: "#ffa781",
  spinnerColor: "#ffa781",
  tableTextColor: "white",
};
